---
title: "**Additional analysis: species-level estimates and visualization**"
output: html_document
---

# Packages

```{r load packages}
pacman::p_load(tidyverse, # tidy family and related packages below
               kableExtra, # nice tables
               gridExtra, # may not use this
               pander,   # nice tables
               metafor,  # package for meta-analysis
               ggtree,
               ggstance,
               ape,      # phylogenetic analysis
               patchwork,   # putting ggplots together - you need to install via devtool
               here,         # making reading files easy
               matrixcalc # matrix calculations
)

# functions
## function to calculate effect sizes
effect_size <- function(m1, m2, sd1, sd2, n1, n2, n, # 12 arguments
                        est , se, p_val, direction, method){

  if(method == "mean_method"){
  
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    s_pool <- sqrt( ((n1-1)*sd1^2 + (n2-1)*sd2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r    
    
  }else if(method == "count_method"){
    
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    s1 <- sqrt(m1)
    s2 <- sqrt(m2)
    s_pool <- sqrt( ((n1-1)*s1^2 + (n2-1)*s2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r     
    
  }else if(method == "percent_method1"){
    
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    m1 <- m1/100
    m2 <- m2/100
    s1 <- 1/sqrt(8)
    s2 <- 1/sqrt(8)
    m1 <- asin(sqrt(m1/100))
    m2 <- asin(sqrt(m2/100))
    s_pool <- sqrt( ((n1-1)*s1^2 + (n2-1)*s2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r 
    
  }else if(method == "percent_method2"){
    
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    m1 <- m1/100
    m2 <- m2/100
    sd1 <- sd1/100
    sd2 <- sd2/100
    s1 <- 1/sqrt(sd1^2/(4*m1*(1-m1)))
    s2 <- 1/sqrt(sd2^2/(4*m2*(1-m2)))
    m1 <- asin(sqrt(m1/100))
    m2 <- asin(sqrt(m2/100))
    s_pool <- sqrt( ((n1-1)*s1^2 + (n2-1)*s2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r 
    
  }else if(method == "proportion_method1"){
    
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    s1 <- 1/sqrt(8)
    s2 <- 1/sqrt(8)
    m1 <- asin(sqrt(m1))
    m2 <- asin(sqrt(m2))
    s_pool <- sqrt( ((n1-1)*s1^2 + (n2-1)*s2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r 
    
  }else if(method == "proportion_method2"){
    
    h <- n/n1 + n/n2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    s1 <- 1/sqrt(sd1^2/(4*m1*(1-m1)))
    s2 <- 1/sqrt(sd2^2/(4*m2*(1-m2)))
    m1 <- asin(sqrt(m1/100))
    m2 <- asin(sqrt(m2/100))
    s_pool <- sqrt( ((n1-1)*s1^2 + (n2-1)*s2^2) / (n - 2) )
    j <- 1 - (3 / (4*n - 9))
    d <- ((m2 - m1) / s_pool) * j
    r_pb <-  d / sqrt(d^2 + h)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r 
    
  }else if(method == "t_method1"){
    

    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    r_pb <- est/sqrt(est^2 + n - 2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r
    
  }else if(method == "t_method2"){
    
    n1 <- n/2
    n2 <- n/2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    r_pb <- est/sqrt(est^2 + n - 2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r
    
  }else if(method == "F_method1"){
    
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    r_pb <- sqrt(est)/sqrt(est + n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r_b = r_b*(direction)
    r <- r_b
  
  }else if(method == "F_method2"){
    
    n1 <- n/2
    n2 <- n/2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    r_pb <- sqrt(est)/sqrt(est + n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r_b = r_b*(direction)
    r <- r_b
    
  }else if(method == "p_method1"){
    
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    t <- qt(1 - p_val, n - 2)
    r_pb <- t/sqrt(t^2 + n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r_b <- r_b*(direction)
    r <- r_b
    
  }else if(method == "p_method2"){
    
    n1 <- n/2
    n2 <- n/2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    t <- qt(1 - p_val, n - 2)
    r_pb <- t/sqrt(t^2 + n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r_b <- r_b*(direction)
    r <- r_b
    
  }else if(method == "correlation_method1"){
    
    r <- est
    
  }else if(method == "correlation_method2"){
    
    r <- 2*sin((pi/6)*est)
    
  }else if(method == "estimate_method1"){
    
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    t <- est/se
    r_pb <- t/sqrt(t^2+ n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r
  
  }else if(method == "estimate_method2"){
    
    n1 <- n/2
    n2 <- n/2
    p <- n1/n # prop for n1
    q <- n2/n # prop for n2
    t <- est/se
    r_pb <- t/sqrt(t^2+ n -2)
    r_b <- r_pb*(sqrt(p*q)/dnorm(qnorm(p)))
    r <- r_b #r_b = r
  
  } 
  
    if(r >= 1){
    # if over 1, we use 0.99
    Zr <- atanh(0.99)

    }else if(r <= -1){

    Zr <- atanh(-0.99) # r = correlation

    } else {

    Zr <- atanh(r) # r = correlation

    }
  
  VZr <- 1 /(n - 3)
  
  data.frame(ri = r, yi = Zr , vi = VZr)
  
}
```



# Data

Just copied code from analysis.qmd.

```{r load data}
# cleaned data
dat <- read.csv(here("data", "clean_data.csv"))
# cleaned tree
tree <- read.tree(here("data", "species_tree.tre"))
```

# Preprocess

Just copied code from analysis.qmd.

```{r}
# calculate estimates
effect2 <- pmap_dfr(list(dat$mean_group_1, dat$mean_group_2, 
                         dat$variance_group_1, dat$variance_group_2, 
                         dat$n_group_1, dat$n_group_2, dat$n, 
                         dat$effect_size_value, dat$effect_size_variance, 
                         dat$effect_size_p_value_numeric, 
                         dat$direction_change, factor(dat$function_needed)), 
                    effect_size)                    
dat <- cbind(dat, effect2)

# renaming X to effectID
colnames(dat)[colnames(dat) == "X"] <- "effectID"

# creating the phylogeny column
dat$phylogeny <-  gsub(" ", "_", dat$species_cleaned)
```

# Plot

Two steps:

1. Estimate species-level effect sizes.

2. Plot tree and add species-level effect size estimates.

These two steps can be done by phylo_model(), which can be found at the following code chunk.

```{r}
# function to estimate species-level effect sizes
phylo_model <- function(data = dat, tree, correlation = 0.5) {
  
  # accounting for within-species correlation
  Vm <- vcalc(vi = data$vi, cluster = data$shared_group, obs = data$effectID, rho = correlation)
  mod <- rma.mv(yi = yi, 
              V = Vm,
              mod = ~ 1,
              data = data,
              random = list(
                            ~ 1 | effectID,
                            ~ 1 | paperID,
                            ~ 1 | phylogeny),
              #R= list(phylogeny = cor_tree),
              test = "t",
              sparse = TRUE)
  
  
  # get random effects
  # dat3 <- dat2[c("phylogeny", "yi", "vi")]
  REs <- ranef(mod)$phylogeny
  
  # calculate means and CIs
  dat <- data.frame(phylogeny = rownames(REs),
                    estimate = mod$beta[1] + REs$intrcpt,
                    se = sqrt((mod$se[1])^2 + (REs$se)^2)) %>%
    mutate(lb = estimate - se * qnorm(1 - 0.05/2), 
           ub = estimate + se * qnorm(1 - 0.05/2)) %>%
    arrange(phylogeny)
  # get species class data
  species_class <- dplyr::distinct(data, phylogeny, .keep_all = TRUE) %>%
    dplyr::select(species_class, phylogeny)
  
  # extract tip labels from the tree and merge with species class
  tip.label <- data.frame(phylogeny = tree$tip.label)  # extract tip label
  species_class2 <- left_join(tip.label, species_class, by = "phylogeny")
  
  return(list(data = dat, class = species_class2))  # return processed data and species class
}

# estimate species-level effect sizes
# you can specify your own correlation coefficient via `correlation`. For illustration purpose, I used 0.5.
result <- phylo_model(data = dat, tree = tree, correlation = 0.5)

# find the significant species
result$data <- result$data %>%
  mutate(
    p_value = 2 * (1 - pnorm(abs(estimate / se))),
    significance = ifelse(p_value < 0.05, "Significant", "NonSignificant")
  )
result$data <- result$data %>%
  mutate(significance_label = ifelse(p_value < 0.05, "*", NA))

# plot tree
p1 <- ggtree(tree, layout = "rectangular", cex = 0.3)

p2 <- p1 %<+% result$class + geom_tiplab(aes(color = species_class), size = 3, align = T, offset = 0.05) + geom_tippoint(aes(color = species_class)) + guides(color = "none")

p3 <- p2 + 
  geom_facet(
    panel = "Effect size", 
    data = result$data, 
    geom = ggstance::geom_pointrangeh,
    mapping = aes(x = estimate, xmin = lb, xmax = ub, color = species_class)
  ) +
  geom_facet(
    panel = "Effect size",
    data = result$data,
    geom = geom_text,
    mapping = aes(x = lb, label = significance_label), 
    hjust = 1.5, size = 3, color = "red"              # adjust position of star *
  ) +
  geom_facet(
    panel = "Effect size",
    data = result$data, 
    geom = geom_vline,
    mapping = aes(xintercept = 0),                    
    linetype = "dashed", color = "gray"
  ) +
  theme_tree2()



# adjust widths of the plot facets as necessary, if it improve visualization 
facet_widths(p3, c(Tree = 0.6, `Effect size` = 0.4))
```

